// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zjknznxxqatggzclqvpf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpqa256bnh4cWF0Z2d6Y2xxdnBmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1MDQ5OTIsImV4cCI6MjA2MzA4MDk5Mn0.dXMPYJhScnQDRaCvGq2TRgJjZTcW1Q4XpsRZCddAiCg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);